import {
  Bus,
  Camera,
  Cake,
  Car,
  Drum,
  Flower,
  Heart,
  Lightbulb,
  MapPin,
  Mic,
  Music,
  Package,
  Palette,
  PartyPopper,
  PenTool,
  Scale,
  Scissors,
  Sofa,
  Sparkles,
  Speaker,
  Truck,
  UserCog,
  Utensils,
  Video,
  Wand2,
  Wine,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";
import type { VendorCategory, VendorStatus } from "./vendor-types";

export const VENDOR_CATEGORIES: VendorCategory[] = [
  "florist",
  "decor",
  "lighting",
  "rentals_furniture",
  "lounge_furniture",
  "stationery",
  "signage",
  "photographer",
  "videographer",
  "photo_booth",
  "dj",
  "live_band",
  "dhol",
  "sound_av",
  "mua_hair",
  "mehndi",
  "pandit",
  "priest_officiant",
  "translator_emcee",
  "baraat_horse",
  "transport",
  "guest_shuttle",
  "bridal_car",
  "cake_dessert",
  "bar_mixology",
  "late_night_food",
  "permits_legal",
  "other",
];

export const VENDOR_CATEGORY_LABEL: Record<VendorCategory, string> = {
  florist: "Florist",
  decor: "Decor",
  transport: "Transport",
  guest_shuttle: "Guest shuttle",
  bridal_car: "Bridal car",
  photographer: "Photographer",
  videographer: "Videographer",
  photo_booth: "Photo booth",
  dj: "DJ",
  live_band: "Live band",
  dhol: "Dhol player",
  sound_av: "Sound / AV",
  lighting: "Lighting",
  mua_hair: "MUA / Hair",
  mehndi: "Mehndi artist",
  baraat_horse: "Baraat horse / car",
  pandit: "Pandit",
  priest_officiant: "Priest / officiant",
  stationery: "Stationery",
  signage: "Signage",
  rentals_furniture: "Rentals / furniture",
  lounge_furniture: "Lounge furniture",
  cake_dessert: "Cake / dessert",
  bar_mixology: "Bar / mixology",
  late_night_food: "Late-night food",
  permits_legal: "Permits / legal",
  translator_emcee: "Translator / emcee",
  other: "Other",
};

// Group categories into broad sections for the index page
export const VENDOR_CATEGORY_GROUP: Record<VendorCategory, string> = {
  florist: "Design",
  decor: "Design",
  lighting: "Design",
  rentals_furniture: "Design",
  lounge_furniture: "Design",
  stationery: "Design",
  signage: "Design",
  photographer: "Capture",
  videographer: "Capture",
  photo_booth: "Capture",
  dj: "Music",
  live_band: "Music",
  dhol: "Music",
  sound_av: "Music",
  mua_hair: "Glam",
  mehndi: "Glam",
  pandit: "Ceremony",
  priest_officiant: "Ceremony",
  translator_emcee: "Ceremony",
  baraat_horse: "Ceremony",
  transport: "Logistics",
  guest_shuttle: "Logistics",
  bridal_car: "Logistics",
  cake_dessert: "F&B",
  bar_mixology: "F&B",
  late_night_food: "F&B",
  permits_legal: "Other",
  other: "Other",
};

export const VENDOR_GROUP_ORDER: string[] = [
  "Design",
  "Capture",
  "Music",
  "Glam",
  "Ceremony",
  "Logistics",
  "F&B",
  "Other",
];

export const VENDOR_CATEGORY_ICON: Record<VendorCategory, LucideIcon> = {
  florist: Flower,
  decor: Palette,
  transport: Truck,
  guest_shuttle: Bus,
  bridal_car: Car,
  photographer: Camera,
  videographer: Video,
  photo_booth: Camera,
  dj: Music,
  live_band: Mic,
  dhol: Drum,
  sound_av: Speaker,
  lighting: Lightbulb,
  mua_hair: Scissors,
  mehndi: Wand2,
  baraat_horse: PartyPopper,
  pandit: Sparkles,
  priest_officiant: Heart,
  stationery: PenTool,
  signage: MapPin,
  rentals_furniture: Sofa,
  lounge_furniture: Sofa,
  cake_dessert: Cake,
  bar_mixology: Wine,
  late_night_food: Utensils,
  permits_legal: Scale,
  translator_emcee: UserCog,
  other: Package,
};

export const VENDOR_STATUSES: VendorStatus[] = [
  "researching",
  "rfp_sent",
  "quoted",
  "shortlisted",
  "booked",
  "completed",
  "declined",
];

export const VENDOR_STATUS_LABEL: Record<VendorStatus, string> = {
  researching: "Researching",
  rfp_sent: "RFP sent",
  quoted: "Quoted",
  shortlisted: "Shortlisted",
  booked: "Booked",
  completed: "Completed",
  declined: "Declined",
};

export const VENDOR_STATUS_VARIANT: Record<
  VendorStatus,
  "default" | "muted" | "success" | "warning" | "destructive" | "secondary" | "outline"
> = {
  researching: "muted",
  rfp_sent: "warning",
  quoted: "warning",
  shortlisted: "default",
  booked: "success",
  completed: "success",
  declined: "destructive",
};
