// Set a public_slug + story_html on the existing demo workspace so /w/<slug>
// returns content. RSVP tokens are auto-generated by the migration default
// for new guests; existing guests already have one (DEFAULT applies on the
// pre-existing rows when the column was added with NOT NULL DEFAULT).

import path from "node:path";
import { fileURLToPath } from "node:url";
import { config as loadEnv } from "dotenv";
import { createClient } from "@supabase/supabase-js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(__dirname, "../..");
loadEnv({ path: path.join(repoRoot, "apps/web/.env.local") });

const sb = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!,
  { auth: { autoRefreshToken: false, persistSession: false } },
);

const SLUG = "nisha-and-hursh";

const STORY = `
<p>We met in 2017 and have been writing our love story ever since. After
a tiny pandemic-era engagement at home and three years of "we should plan
something", we&rsquo;re finally bringing everyone together — for two days
of food, dance, and the kind of joy you only get from your favorite people
in one room.</p>

<p>The plan: an Indian-Catalan weekend in Barcelona, September 2027.
Sangeet on Saturday at Casa Del Mar by the sea, ceremony + reception on
Sunday at Mas de Sant Llei in the hills.</p>

<p>We can&rsquo;t wait to see you there.</p>
`.trim();

async function main() {
  const { data: workspace } = await sb
    .from("workspaces")
    .select("id, name, wedding_date, public_slug")
    .limit(1)
    .maybeSingle();
  if (!workspace) throw new Error("no workspace; run pnpm db:seed first");

  const { error } = await sb
    .from("workspaces")
    .update({ public_slug: SLUG, story_html: STORY })
    .eq("id", workspace.id);
  if (error) throw error;

  console.log(`✓ workspace "${workspace.name}" published at /w/${SLUG}`);

  // Confirm rsvp_tokens
  const { data: guests } = (await sb
    .from("guests")
    .select("id, rsvp_token")) as unknown as {
    data: { id: string; rsvp_token: string | null }[] | null;
  };
  const total = guests?.length ?? 0;
  const withTokens = (guests ?? []).filter((g) => g.rsvp_token).length;
  console.log(`✓ guests: ${total} total, ${withTokens} have rsvp_token`);

  console.log("");
  console.log(`Public site: http://localhost:3200/w/${SLUG}`);
  console.log("Done.");
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
