// /estimator — picks the right view for THIS workspace.
//
// Two surfaces existed historically and both still need to work:
//
//   1. Astia-PDF view (B2B couple, planner-served) — reads from
//      `budget_estimates` (rows seeded from PDFs via
//      supabase/seed/import_astha_estimates.ts). This is the OG view that
//      shipped with the planner-mode product. Hursh & Nisha + Astia's
//      other workspaces have data here.
//
//   2. AI-baseline drill-down (B2C couple, self-serve) — reads from
//      `budget_lines` (rows generated by /api/budget-lines/generate-baseline).
//      Kyle, John, Rachel, etc. have data here once they hit "Generate
//      baseline" on /budget.
//
// Same workspace can technically have both. We prefer the planner-seeded
// view when it exists because that's the more authoritative data for that
// kind of customer.

import Link from "next/link";
import { ArrowRight, Columns, FileText, Plus, Sparkles, Coins } from "lucide-react";
import { createClient } from "@/lib/supabase/server";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import {
  documentBaseline,
  documentOverrideDelta,
  documentTotal,
  formatEUR,
  type EstimateDocument,
  type BudgetEstimateRow,
} from "@/lib/estimator-types";
import { type BudgetLineRow } from "@/lib/autopilot-types";
import { EstimatorDrillDown } from "@/components/estimator/estimator-drill-down";

export const dynamic = "force-dynamic";

type EstimateRow = Pick<
  BudgetEstimateRow,
  | "id"
  | "name"
  | "source_label"
  | "scenario_summary"
  | "cover_emoji"
  | "guest_count"
  | "start_date"
  | "end_date"
  | "sections"
  | "baseline_total_eur"
  | "sort_order"
>;

export default async function EstimatorPage() {
  const supabase = createClient();

  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) return null;

  const { data: profile } = await supabase
    .from("users")
    .select("workspace_id")
    .eq("id", user.id)
    .maybeSingle();
  if (!profile?.workspace_id) return null;

  // ─── 1. Try the planner-seeded budget_estimates first ─────────────────
  const { data: estimates } = await supabase
    .from("budget_estimates")
    .select(
      "id, name, source_label, scenario_summary, cover_emoji, guest_count, start_date, end_date, sections, baseline_total_eur, sort_order",
    )
    .eq("is_active", true)
    .order("sort_order", { ascending: true });
  const list: EstimateRow[] = (estimates as EstimateRow[] | null) ?? [];

  if (list.length > 0) {
    // Planner-seeded view (Hursh & Nisha, Sara & Marcus, etc.)
    return <PlannerSeededView list={list} />;
  }

  // ─── 2. Fall back to the AI-baseline drill-down on budget_lines ──────
  const sbWs = supabase as unknown as {
    from: (t: string) => {
      select: (cols: string) => {
        eq: (col: string, val: string) => {
          maybeSingle: () => Promise<{
            data: {
              name: string;
              base_currency: string;
              budget_target_eur: number | null;
              guest_count_estimate: number | null;
            } | null;
          }>;
        };
      };
    };
  };
  const { data: workspace } = await sbWs
    .from("workspaces")
    .select("name, base_currency, budget_target_eur, guest_count_estimate")
    .eq("id", profile.workspace_id)
    .maybeSingle();

  const currency = workspace?.base_currency ?? "USD";
  const target = workspace?.budget_target_eur ?? null;
  const guestCount = workspace?.guest_count_estimate ?? null;

  const sbLines = supabase as unknown as {
    from: (t: string) => {
      select: (cols: string) => {
        eq: (col: string, val: string) => Promise<{
          data: BudgetLineRow[] | null;
        }>;
      };
    };
  };
  const { data: linesRaw } = await sbLines
    .from("budget_lines")
    .select(
      "id, workspace_id, org_id, parent_line_id, category, label, qty, unit_price_eur, total_eur, amount_estimated, amount_committed, amount_paid, vendor_id, status, source, notes, sort_order, metadata, created_at, updated_at",
    )
    .eq("workspace_id", profile.workspace_id);
  const lines = (linesRaw ?? []) as BudgetLineRow[];

  // Vendors for the per-line dropdown
  const sbVendors = supabase as unknown as {
    from: (t: string) => {
      select: (cols: string) => {
        eq: (col: string, val: string) => Promise<{
          data: Array<{
            id: string;
            name: string;
            category: string | null;
            quoted_price_eur: number | null;
          }> | null;
        }>;
      };
    };
  };
  let vendors: Array<{
    id: string;
    name: string;
    category: string | null;
    quoted_price_eur: number | null;
  }> = [];
  try {
    const { data } = await sbVendors
      .from("vendors")
      .select("id, name, category, quoted_price_eur")
      .eq("workspace_id", profile.workspace_id);
    vendors = (data ?? []).map((v) => ({
      id: v.id,
      name: v.name,
      category: v.category ?? null,
      quoted_price_eur: v.quoted_price_eur ?? null,
    }));
  } catch {
    vendors = [];
  }

  // Linked tasks for the drill-down (best-effort — column may not be live yet)
  const sbTasks = supabase as unknown as {
    from: (t: string) => {
      select: (cols: string) => {
        eq: (col: string, val: string) => Promise<{
          data: Array<{
            id: string;
            title: string;
            status: string;
            budget_line_id: string | null;
            estimated_cost: number | null;
          }> | null;
          error: { message: string } | null;
        }>;
      };
    };
  };
  let linkedTasks: Array<{
    id: string;
    title: string;
    status: string;
    budget_line_id: string | null;
    estimated_cost: number | null;
  }> = [];
  try {
    const { data, error } = await sbTasks
      .from("planning_tasks")
      .select("id, title, status, budget_line_id, estimated_cost")
      .eq("workspace_id", profile.workspace_id);
    if (!error && data) {
      linkedTasks = data.filter((t) => t.budget_line_id);
    }
  } catch {
    linkedTasks = [];
  }

  if (lines.length === 0) {
    // Genuinely empty — point to /budget for AI baseline gen
    return (
      <div className="space-y-6">
        <header>
          <div className="text-[11px] uppercase tracking-[0.25em] text-stone-500">
            Forecast
          </div>
          <h1 className="mt-1 font-serif text-4xl font-light tracking-tight md:text-5xl">
            Estimator
          </h1>
          <p className="mt-2 max-w-2xl text-sm text-muted-foreground">
            Where your wedding lands today: AI-estimated lines + locked-in
            vendor quotes + paid amounts.
          </p>
        </header>
        <Card>
          <CardContent className="py-12 text-center">
            <Coins className="mx-auto mb-3 h-8 w-8 text-stone-300" />
            <h3 className="font-serif text-xl font-light text-stone-800">
              No budget yet
            </h3>
            <p className="mx-auto mt-2 max-w-sm text-sm text-stone-500">
              Build your starter budget at{" "}
              <Link href="/budget" className="font-medium text-rose-700 underline">
                /budget
              </Link>{" "}
              first. AI generates a personalized 70+ line tree from your guest
              count + region in seconds.
            </p>
            <Link
              href="/budget"
              className="mt-5 inline-flex items-center gap-1.5 rounded-full bg-stone-900 px-4 py-2 text-xs font-medium text-white transition hover:bg-stone-800"
            >
              Build my budget <ArrowRight className="h-3 w-3" />
            </Link>
          </CardContent>
        </Card>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <header>
        <div className="text-[11px] uppercase tracking-[0.25em] text-stone-500">
          Forecast · scenario builder
        </div>
        <h1 className="mt-1 font-serif text-4xl font-light tracking-tight md:text-5xl">
          Estimator
        </h1>
        <p className="mt-2 max-w-2xl text-sm text-muted-foreground">
          <span className="font-medium text-stone-700">Live forecast</span> —
          what the wedding might actually cost, recalc'd as vendor quotes
          land. Click a category to drill in and swap vendors. For your
          fixed plan, see <a className="underline" href="/budget">/budget</a>;
          for actuals, see <a className="underline" href="/spend">/spend</a>.
        </p>
      </header>

      <EstimatorDrillDown
        initialLines={lines}
        vendors={vendors}
        baseCurrency={currency}
        target={target}
        guestCount={guestCount}
        linkedTasks={linkedTasks}
      />
    </div>
  );
}

// ─── The OG planner-seeded view ──────────────────────────────────────
// Lifted verbatim from commit 0263ca6:apps/web/app/(app)/estimator/page.tsx
// so Hursh + Astia's other workspaces see exactly what they saw before.
function PlannerSeededView({ list }: { list: EstimateRow[] }) {
  return (
    <div className="space-y-6">
      <header className="flex flex-wrap items-start justify-between gap-4">
        <div>
          <div className="text-[11px] uppercase tracking-[0.25em] text-stone-500">
            Honest budget · planner-seeded · couple-edited
          </div>
          <h1 className="mt-1 font-serif text-4xl font-light tracking-tight md:text-5xl">
            Estimator
          </h1>
          <p className="mt-2 max-w-2xl text-sm text-muted-foreground">
            Estimated initial budgets for your scenarios. Toggle anything off,
            override any number — your edits stay here, they don&apos;t touch
            the master pricing template.
          </p>
        </div>
        <div className="flex flex-wrap items-center gap-2">
          {list.length >= 2 && (
            <Link
              href="/estimator/compare"
              className="inline-flex items-center gap-2 rounded-full border border-stone-300 bg-white px-4 py-2 text-sm font-medium text-stone-800 transition hover:border-stone-900 hover:shadow-sm"
            >
              <Columns className="h-4 w-4" />
              Compare
            </Link>
          )}
          <Link
            href="/estimator/new"
            className="inline-flex items-center gap-2 rounded-full bg-stone-900 px-4 py-2 text-sm font-medium text-white transition hover:bg-stone-700"
          >
            <Plus className="h-4 w-4" />
            New estimate
          </Link>
        </div>
      </header>

      <div className="grid gap-4 md:grid-cols-2">
        {list.map((est) => {
          const doc = (est.sections ?? { version: 1, sections: [] }) as EstimateDocument;
          const total = documentTotal(doc);
          const baseline = documentBaseline(doc);
          const delta = documentOverrideDelta(doc);
          const printedBaseline = est.baseline_total_eur ?? baseline;

          return (
            <Link
              key={est.id}
              href={`/estimator/${est.id}`}
              className="group block"
            >
              <Card className="h-full transition hover:-translate-y-0.5 hover:shadow-md">
                <CardContent className="space-y-4 py-6">
                  <div className="flex items-start justify-between gap-3">
                    <div className="flex items-center gap-3">
                      <div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl bg-gradient-to-br from-rose-50 via-white to-amber-50 text-2xl">
                        {est.cover_emoji ?? "💍"}
                      </div>
                      <div>
                        <h3 className="font-serif text-2xl">{est.name}</h3>
                        <p className="mt-0.5 text-xs text-muted-foreground">
                          {est.scenario_summary}
                        </p>
                      </div>
                    </div>
                    <ArrowRight className="h-5 w-5 shrink-0 text-stone-400 transition group-hover:translate-x-0.5 group-hover:text-stone-700" />
                  </div>

                  <div className="rounded-xl border border-stone-200 bg-stone-50/50 p-4">
                    <div className="flex items-baseline justify-between">
                      <div className="text-[10px] uppercase tracking-[0.2em] text-stone-500">
                        Effective total
                      </div>
                      <div className="font-serif text-3xl font-medium tracking-tight">
                        {formatEUR(total)}
                      </div>
                    </div>
                    <div className="mt-3 flex flex-wrap items-center gap-3 text-xs">
                      <span className="text-muted-foreground">
                        baseline {formatEUR(printedBaseline)}
                      </span>
                      {Math.abs(delta) > 0.5 && (
                        <Badge
                          variant={delta < 0 ? "success" : "warning"}
                          className="text-[10px]"
                        >
                          {delta < 0 ? "−" : "+"}
                          {formatEUR(Math.abs(delta))} your edits
                        </Badge>
                      )}
                      {est.guest_count && (
                        <span className="text-muted-foreground">
                          ·{" "}
                          {Math.round(total / est.guest_count).toLocaleString()}{" "}
                          <span className="text-[10px] uppercase">€/guest</span>
                        </span>
                      )}
                    </div>
                  </div>

                  <div className="flex flex-wrap items-center gap-2 text-[11px] text-stone-500">
                    <FileText className="h-3 w-3" />
                    <span>{est.source_label}</span>
                    <span>·</span>
                    <span>
                      {doc.sections.length} sections,{" "}
                      {doc.sections.reduce((a, s) => a + s.lines.length, 0)} lines
                    </span>
                  </div>
                </CardContent>
              </Card>
            </Link>
          );
        })}
      </div>

      <Card className="border-rose-200 bg-gradient-to-br from-rose-50 via-white to-amber-50">
        <CardContent className="flex flex-wrap items-start gap-4 py-5">
          <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-rose-100 text-rose-700">
            <Sparkles className="h-5 w-5" />
          </div>
          <div className="flex-1">
            <div className="flex flex-wrap items-center gap-2">
              <h3 className="font-serif text-lg">How the Estimator works</h3>
              <Badge variant="muted" className="text-[10px]">
                Local-only
              </Badge>
            </div>
            <ul className="mt-1 space-y-1 text-sm text-stone-700">
              <li>
                <span className="font-medium">Baseline</span>: the original
                quoted price stays locked + visible as a reference.
              </li>
              <li>
                <span className="font-medium">Override</span>: click any number
                to edit. Your edit stacks on top of the baseline.
              </li>
              <li>
                <span className="font-medium">Toggle</span>: uncheck a line to
                exclude it from your total without losing the data.
              </li>
              <li>
                <span className="font-medium">Local-only</span>: changes here
                don&apos;t touch the master pricing template or your /pricing
                scenarios.
              </li>
            </ul>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
